CREATE TABLE IF NOT EXISTS translations (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    language TEXT NOT NULL,
    canon TEXT NOT NULL,
    source TEXT,
    license TEXT,
    metadata_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    abbreviation TEXT NOT NULL,
    name TEXT NOT NULL,
    testament TEXT NOT NULL,
    canon_order INTEGER NOT NULL,
    chapter_count INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS book_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES books (id) ON DELETE CASCADE,
    alias TEXT NOT NULL,
    normalized_alias TEXT NOT NULL,
    UNIQUE (book_id, normalized_alias)
);

CREATE INDEX IF NOT EXISTS idx_book_aliases_normalized_alias
    ON book_aliases (normalized_alias);

CREATE TABLE IF NOT EXISTS verses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    translation_id TEXT NOT NULL REFERENCES translations (id) ON DELETE CASCADE,
    book_id BIGINT NOT NULL REFERENCES books (id) ON DELETE CASCADE,
    chapter INTEGER NOT NULL,
    verse INTEGER NOT NULL,
    text TEXT NOT NULL,
    UNIQUE (translation_id, book_id, chapter, verse)
);

CREATE INDEX IF NOT EXISTS idx_verses_lookup
    ON verses (translation_id, book_id, chapter, verse);
